### ISSUE TITLE
IssueResource

### ISSUE THREAD

**Issue by danielptm** [youthbo/JerseyProjectFinal#1]
Kan inte skapa en Issue enligt instruktionerna i kommentar ovanför metoden create().

När jag skickar en uri med Headers
Content-Type : application/json

och sen body

{
   description:"A descriptionf"
}

Jag får exception

HTTP Status 500 - org.springframework.orm.jpa.JpaSystemException: could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement

**Comment by danielptm** [comment]
Kan du kanske skriva ner precis hur din body och headers ser ut, för att få den här att funka?

**Comment by danielptm** [comment]
update() verkar att fungera fin

**Comment by youthbo** [comment]
Hej, jag använder precis samma body som dig.Kan du skicka alla Exception?

**Comment by danielptm** [comment]
Jag gör det om en stund. Det är kanske nånting konstigt med min miljö. För att jag har samma problem med create() med Irinas och Imans metoder också....

**Comment by danielptm** [comment]
Men de andra metoder funkar

**Comment by danielptm** [comment]
Jag skickar 

uri
http://127.0.0.1:8080/issues

Headers
Content-Type Application/json

Body
{
	"description":"issue2"
}

Och jag får

HTTP Status 500 - org.springframework.orm.jpa.JpaSystemException: could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement

**Comment by IrinaMix** [comment]
för mig det funkar

**Comment by danielptm** [comment]
Jag tror att det finns nånting konstigt med min miljö

**Comment by IrinaMix** [comment]
kanske

**Comment by IrinaMix** [comment]
men Iman också sa angående min teamResource att det funkar inte

**Comment by danielptm** [comment]
Var det med addTeam()

**Comment by danielptm** [comment]
?

**Comment by danielptm** [comment]
Jag tror att jag har hittat problemet i mitt, fall, men det skulle vara konstigt att det funkar för er....

**Comment by IrinaMix** [comment]
jag, det konstigt

**Comment by youthbo** [comment]
Bra!

**Comment by danielptm** [comment]
Inte säker varför precis, men jag byggde om databasen, och nu funkar det.
