### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by danielptm** [youthbo/JerseyProjectFinal#2]
Jag förstår inte, hur man ska använda addUser() metoden. Hur borde URI ser ut? Och hur borde body se ut?

**Comment by imantahriri** [comment]
uri : /users
body:
{
    "firstname" : "xxx",
    "lastname" : "xxx",
    "username" : "xxxx",
    "teamname" : "xxxx"
}
om team name finns, hämtas det annars skapas ett nytt team med det här namnet.

**Comment by danielptm** [comment]
Thanks
