### ISSUE TITLE
Team resource

### ISSUE THREAD

**Issue by danielptm** [youthbo/JerseyProjectFinal#4]
Kan inte få addTeam() att fungera. 

I Postman använder jag den här

URI
http://127.0.0.1:8080/teams

Headers
Content-Type application/json

och sen i Body

{
	"name":"eagles",
	"status":"active"
	
}

Jag får exception
HTTP Status 500 - se.plushogskolan.service.ServiceException: Could not add team: eagles

**Comment by danielptm** [comment]
Hur ser den här request ut, kan du skriva hur det ser ut i headers och i body?

**Comment by danielptm** [comment]
update() och getAllTeams() metoden funkar bra

**Comment by IrinaMix** [comment]
jag har upload sista version, så du kan ladda ner den, det finns comments

**Comment by danielptm** [comment]
Jag vet inte varför men jag kan inte få det att funka. Jag får den här exception...


2016-12-15 12:48:05.513  WARN 1632 --- [nio-8080-exec-4] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1364, SQLState: HY000
2016-12-15 12:48:05.513 ERROR 1632 --- [nio-8080-exec-4] o.h.engine.jdbc.spi.SqlExceptionHelper   : Field 'id' doesn't have a default value

**Comment by danielptm** [comment]
HTTP Status 409 - Conflict

**Comment by imantahriri** [comment]
conflict händer när man skickar duplicerat description

**Comment by imantahriri** [comment]
också jag fick "Field 'id' doesn't have a default value" när använde fel database name!

**Comment by IrinaMix** [comment]
om status conflict då du skickar duplicerat team name , so Iman sagt

**Comment by IrinaMix** [comment]
Iman, vilken metod  har du testad

**Comment by danielptm** [comment]
Jag vet, men jag kollar i databasen, och namnet finns inte.

**Comment by IrinaMix** [comment]
har du skickar bara team name eller status också?

**Comment by danielptm** [comment]
bara team name

**Comment by danielptm** [comment]
Men jag tror inte att det har nånting att göra med name

**Comment by danielptm** [comment]
Jag tror att det har nånting att göra med id

**Comment by danielptm** [comment]
För i min konsol det skrivs ut det här meddelande

2016-12-15 12:48:05.513 WARN 1632 --- [nio-8080-exec-4] o.h.engine.jdbc.spi.SqlExceptionHelper : SQL Error: 1364, SQLState: HY000
2016-12-15 12:48:05.513 ERROR 1632 --- [nio-8080-exec-4] o.h.engine.jdbc.spi.SqlExceptionHelper : Field 'id' doesn't have a default value

**Comment by IrinaMix** [comment]
jag vet inte varför det händer, för mig det funkar bra.. ska försöks hitta fel

**Comment by danielptm** [comment]
Det är konstigt för att det är bara för create, de andra metoder funkar bra, så det kan inte vara fel databas namn

**Comment by danielptm** [comment]
Jag byggde om databasen och nu funkar det. Vet inte varför det inte funkade.

**Comment by danielptm** [comment]
Tack för hjälpen!
